const genres = {
  rock: ["Classic Rock", "Progressive Rock", "Hard Rock"],
  metal: [
    "Metal",
    "Classic Metal",
    "Thrash Metal",
    "Death Metal",
    "Progressive Metal",
    "Symphonic Metal",
    "Doom Metal",
    "Folk Metal",
    "Black Metal",
  ],
  folk: ["folk"],
  country: ["Country"],
  rap: ["Rap"],
  hiphop: ["Hip Hop"],
  classical: ["Classical"],
  pop: ["Pop", "Power Pop"],
  alternative: ["Alternative Rock"],
  punk: ["Punk"],
  soundtrack: ["Soundtrack"],
  electronic: ["Electronic"],
  blues: ["Blues"],
  jazz: ["Jazz", "Jazz Fusion"],
  dance: ["Dance"],
  reggae: ["Reggae"],
  funk: ["Funk"],
  disco: ["Disco"],
  instrumental: ["Instrumental"],
  world: ["World"],
  ska: ["Ska"],
  baroque: ["Baroque"],
  industrial: ["Industrial"],
  dubstep: ["Dubstep"],
  bluegrass: ["Bluegrass"],
  newwave: ["New Wave"],
  grunge: ["Grunge"],
};
